version: '3.8'

services:
  app:
    container_name: imn-production-app-prod
    build:
      context: ./services/web/
      dockerfile: Dockerfile.prod
    volumes:
      - ./services/web/backup/backups:/app/backup/backups
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    expose:
      - 8080
    restart: always
    command: alembic upgrade head && gunicorn app.main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8080

  nginx:
    build: ./services/nginx
    ports:
      - 80:80
    depends_on:
      - app
    restart: always
