"""add timestamp

Revision ID: 6cf58c47d50f
Revises: c05087ba3986
Create Date: 2024-06-14 07:02:10.326222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cf58c47d50f'
down_revision = 'c05087ba3986'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity_mesin', sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('activity_mesin', sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True))
    op.add_column('mesin_log', sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('mesin_log', sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True))
    op.add_column('mesin_status', sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('mesin_status', sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True))
    op.add_column('operator_status', sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('operator_status', sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('operator_status', 'time_updated')
    op.drop_column('operator_status', 'time_created')
    op.drop_column('mesin_status', 'time_updated')
    op.drop_column('mesin_status', 'time_created')
    op.drop_column('mesin_log', 'time_updated')
    op.drop_column('mesin_log', 'time_created')
    op.drop_column('activity_mesin', 'time_updated')
    op.drop_column('activity_mesin', 'time_created')
    # ### end Alembic commands ###
