"""dbinit

Revision ID: c05087ba3986
Revises: 
Create Date: 2023-03-15 04:05:44.770610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c05087ba3986'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mesin',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('tonase', sa.Integer(), nullable=True),
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mesin_id'), 'mesin', ['id'], unique=False)
    op.create_table('operator',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operator_id'), 'operator', ['id'], unique=False)
    op.create_table('tooling',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('customer', sa.String(), nullable=True),
    sa.Column('part_no', sa.String(), nullable=True),
    sa.Column('part_name', sa.String(), nullable=True),
    sa.Column('child_part_name', sa.String(), nullable=True),
    sa.Column('kode_tooling', sa.String(), nullable=True),
    sa.Column('common_tooling_name', sa.String(), nullable=True),
    sa.Column('proses', sa.String(), nullable=True),
    sa.Column('std_jam', sa.Integer(), nullable=True),
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tooling_id'), 'tooling', ['id'], unique=False)
    op.create_table('mesin_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tooling_id', sa.String(), nullable=True),
    sa.Column('mesin_id', sa.String(), nullable=True),
    sa.Column('operator_id', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('output', sa.Integer(), nullable=True),
    sa.Column('downtime_category', sa.String(), nullable=False),
    sa.Column('category', sa.Enum('START', 'STOP', name='category'), nullable=True),
    sa.ForeignKeyConstraint(['mesin_id'], ['mesin.id'], ),
    sa.ForeignKeyConstraint(['operator_id'], ['operator.id'], ),
    sa.ForeignKeyConstraint(['tooling_id'], ['tooling.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mesin_log_id'), 'mesin_log', ['id'], unique=False)
    op.create_table('operator_status',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('RUNNING', 'IDLE', 'DOWNTIME', name='operator_status_enum'), nullable=False),
    sa.Column('last_tooling_id', sa.String(), nullable=False),
    sa.Column('last_mesin_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['operator.id'], ),
    sa.ForeignKeyConstraint(['last_mesin_id'], ['mesin.id'], ),
    sa.ForeignKeyConstraint(['last_tooling_id'], ['tooling.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operator_status_id'), 'operator_status', ['id'], unique=False)
    op.create_table('activity_mesin',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mesin_id', sa.String(), nullable=False),
    sa.Column('operator_id', sa.String(), nullable=False),
    sa.Column('start_time_id', sa.Integer(), nullable=False),
    sa.Column('stop_time_id', sa.Integer(), nullable=False),
    sa.Column('output', sa.Integer(), nullable=False),
    sa.Column('reject', sa.Integer(), nullable=False),
    sa.Column('rework', sa.Integer(), nullable=False),
    sa.Column('coil_no', sa.String(), nullable=True),
    sa.Column('lot_no', sa.String(), nullable=True),
    sa.Column('pack_no', sa.String(), nullable=True),
    sa.Column('downtime_category', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['mesin_id'], ['mesin.id'], ),
    sa.ForeignKeyConstraint(['operator_id'], ['operator.id'], ),
    sa.ForeignKeyConstraint(['start_time_id'], ['mesin_log.id'], ),
    sa.ForeignKeyConstraint(['stop_time_id'], ['mesin_log.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_mesin_start_time_id'), 'activity_mesin', ['start_time_id'], unique=False)
    op.create_index(op.f('ix_activity_mesin_stop_time_id'), 'activity_mesin', ['stop_time_id'], unique=False)
    op.create_table('mesin_status',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('RUNNING', 'IDLE', 'SETUP', name='status'), nullable=True),
    sa.Column('last_start_id', sa.Integer(), nullable=False),
    sa.Column('last_stop_id', sa.Integer(), nullable=False),
    sa.Column('last_tooling_id', sa.String(), nullable=False),
    sa.Column('last_operator_id', sa.String(), nullable=True),
    sa.Column('category_downtime', sa.String(), nullable=True),
    sa.Column('displayed_status', sa.Enum('RUNNING', 'IDLE', 'DOWNTIME', name='displayed_status'), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['mesin.id'], ),
    sa.ForeignKeyConstraint(['last_operator_id'], ['operator.id'], ),
    sa.ForeignKeyConstraint(['last_start_id'], ['mesin_log.id'], ),
    sa.ForeignKeyConstraint(['last_stop_id'], ['mesin_log.id'], ),
    sa.ForeignKeyConstraint(['last_tooling_id'], ['tooling.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mesin_status_id'), 'mesin_status', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mesin_status_id'), table_name='mesin_status')
    op.drop_table('mesin_status')
    op.drop_index(op.f('ix_activity_mesin_stop_time_id'), table_name='activity_mesin')
    op.drop_index(op.f('ix_activity_mesin_start_time_id'), table_name='activity_mesin')
    op.drop_table('activity_mesin')
    op.drop_index(op.f('ix_operator_status_id'), table_name='operator_status')
    op.drop_table('operator_status')
    op.drop_index(op.f('ix_mesin_log_id'), table_name='mesin_log')
    op.drop_table('mesin_log')
    op.drop_index(op.f('ix_tooling_id'), table_name='tooling')
    op.drop_table('tooling')
    op.drop_index(op.f('ix_operator_id'), table_name='operator')
    op.drop_table('operator')
    op.drop_index(op.f('ix_mesin_id'), table_name='mesin')
    op.drop_table('mesin')
    # ### end Alembic commands ###
