"""remove downtime operator

Revision ID: 7b3c59f3297d
Revises: 701c51e39290
Create Date: 2023-03-01 05:32:45.391343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b3c59f3297d'
down_revision = '701c51e39290'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('continued_downtime_operator')
    op.drop_table('last_downtime_operator')
    op.drop_table('utility_operator')
    op.add_column('continued_downtime_mesin', sa.Column('operator_id', sa.String(), nullable=False))
    op.create_foreign_key(None, 'continued_downtime_mesin', 'operator', ['operator_id'], ['id'])
    op.add_column('last_downtime_mesin', sa.Column('operator_id', sa.String(), nullable=False))
    op.create_foreign_key(None, 'last_downtime_mesin', 'operator', ['operator_id'], ['id'])
    op.add_column('utility_mesin', sa.Column('operator_id', sa.String(), nullable=False))
    op.create_foreign_key(None, 'utility_mesin', 'operator', ['operator_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'utility_mesin', type_='foreignkey')
    op.drop_column('utility_mesin', 'operator_id')
    op.drop_constraint(None, 'last_downtime_mesin', type_='foreignkey')
    op.drop_column('last_downtime_mesin', 'operator_id')
    op.drop_constraint(None, 'continued_downtime_mesin', type_='foreignkey')
    op.drop_column('continued_downtime_mesin', 'operator_id')
    op.create_table('utility_operator',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('operator_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('start_time_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('stop_time_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('output', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('reject', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('rework', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['operator_id'], ['operator.id'], name='utility_operator_operator_id_fkey'),
    sa.ForeignKeyConstraint(['start_time_id'], ['start.id'], name='utility_operator_start_time_id_fkey'),
    sa.ForeignKeyConstraint(['stop_time_id'], ['stop.id'], name='utility_operator_stop_time_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='utility_operator_pkey')
    )
    op.create_table('last_downtime_operator',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('operator_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('start_time_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('stop_time_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('reject', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('rework', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('downtime_category', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['operator_id'], ['operator.id'], name='last_downtime_operator_operator_id_fkey'),
    sa.ForeignKeyConstraint(['start_time_id'], ['stop.id'], name='last_downtime_operator_start_time_id_fkey'),
    sa.ForeignKeyConstraint(['stop_time_id'], ['start.id'], name='last_downtime_operator_stop_time_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='last_downtime_operator_pkey')
    )
    op.create_table('continued_downtime_operator',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('operator_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('start_time_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('stop_time_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('reject', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('rework', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('downtime_category', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['operator_id'], ['operator.id'], name='continued_downtime_operator_operator_id_fkey'),
    sa.ForeignKeyConstraint(['start_time_id'], ['stop.id'], name='continued_downtime_operator_start_time_id_fkey'),
    sa.ForeignKeyConstraint(['stop_time_id'], ['stop.id'], name='continued_downtime_operator_stop_time_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='continued_downtime_operator_pkey')
    )
    # ### end Alembic commands ###
