"""add coil and lot no

Revision ID: c464bedbf2fd
Revises: 7b3c59f3297d
Create Date: 2023-03-01 20:59:59.802610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c464bedbf2fd'
down_revision = '7b3c59f3297d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('utility_mesin', sa.Column('coil_no', sa.Integer(), nullable=True))
    op.add_column('utility_mesin', sa.Column('lot_no', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('utility_mesin', 'lot_no')
    op.drop_column('utility_mesin', 'coil_no')
    # ### end Alembic commands ###
